#!/bin/bash

RANDOM=$(date '+%s')
WORDFILE="$HOME/.wordlist"
NUMWORDS=${1:-2} # The arg should be the number of words needed

if [ ! -e "$WORDFILE" ]; then
	aspell dump master | tr -d '[:punct:]' | sort | uniq >"$WORDFILE"
fi

shuf -n "$NUMWORDS" "$WORDFILE" | sed ':a;N;$!ba;s/\n/-/g'
