#!/bin/bash 

width=$(xdpyinfo | awk '/dimensions/{print $2}' | awk -F'x' '{print $1}')
height=$(xdpyinfo | awk '/dimensions/{print $2}' | awk -F'x' '{print $2}')

t_height=20
border=5

xfce4-terminal --hide-borders
wmctrl -r :ACTIVE: -e 0,0,$((height-t_height)),$width,$t_height
wmctrl -r :ACTIVE: -b add,above

#it is ONE pixel too narrow and nothing helps :(
